### PR TITLE
add operator label images

### PR DESCRIPTION
**Pull request by sjenning**
also opening to test brand new CI integration

@RobertKrawitz

### CODE REVIEW

**Comment by sjenning** [comment]
hmm presubmit jobs didn't run....

**Comment by sjenning** [comment]
/retest
/hold
until after beta3 cut on 3/29

**Comment by RobertKrawitz** [comment]
/hold
No sense in endless retesting that's bound to fail.

**Comment by sjenning** [comment]
had to sync image pull spec between `image-references` and the deployment

**Comment by RobertKrawitz** [comment]
@sjenning what for here?

**Comment by sjenning** [comment]
@RobertKrawitz https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_etcd-quorum-guard/4/pull-ci-openshift-etcd-quorum-guard-master-e2e-aws/65#openshift-tests-featureplatformsmoke-managed-cluster-should-ensure-pods-use-images-from-our-release-image-with-proper-imagepullpolicy-suiteopenshiftconformanceparallel

Since the `etcd-quorum-gaurd` image is just `origin-base` + manifests, we should just use it to maintain the established pattern.  Otherwise someone will come back later and say "wait, this image isn't even being used by anything in the cluster" and do something crazy.

**Comment by RobertKrawitz** [comment]
I see.
/lgtm

**Pull request merged**
